language: csharp
solution: RandomGenerator/RandomGenerator.sln
deploy:
  provider: releases
  api_key: "travis encrypt <0b504a609b6ce615fe5f4f301cd421794b1d1551>"
  file: "RandomGenerator/RandomGenerator/bin/Debug/RandomGenerator.exe"
  skip_cleanup: true
  travis encrypt -r Arnotjevleesch/Arnotes --org